language: node_js
node_js:
  - '6' # lts

cache:
  yarn: true

matrix:
  fast_finish: true

script:
  - yarn run lint
  - yarn run test:prebuild
  - HASH=$(cksum dist/index.js)
  - yarn run build
  - if [[ "$(cksum dist/index.js)" != $HASH ]]; then exit 1; fi
  - yarn run test:postbuild

branches:
  only:
    - feature/travis-ci

# deploy:
#   - provider: npm
#     email: 'xxxx'
#     api_key: 'xxxx'
#     skip_cleanup: true
#     on:
#       repo: Swizz/snabbdom-pragma
#       branch: master
#       tags: true
#
#   - provider: releases
#     user: 'xxxx'
#     password: 'xxxx'
#     skip_cleanup: true
#     on:
#       repo: Swizz/snabbdom-pragma
#       branch: master
#       tags: true
